// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beta': string;
  'container': string;
  'libInfo': string;
  'main-container': string;
  'result': string;
  'skillToolTipPopover': string;
  'tipLabel': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
